### ISSUE TITLE
Suggestion: option to import and export authentication

### ISSUE THREAD

**Issue by franco27** [X1nto/Mauth#52] opened 2023-11-11 23:34 UTC
In your application, it is unfortunate that one cannot export and import their authentications or the data from your application to a file, in order to be able to restore them later.

**Comment by X1nto** [comment] 2023-11-12 09:36
Duplicate of #10

**Closed by X1nto** 2023-11-12 09:36 UTC

**Comment by franco27** [comment] 2023-11-12 10:27
The feature I suggested to you is not for importing a file from another authentication application, but for restoring a file that contains the authentications of your application in order to restore them in another installation or on another device. 
The purpose is to retrieve them in your application.
