### ISSUE TITLE
[Feature Request] Export as file

### ISSUE THREAD

**Issue by pabloscloud** [X1nto/Mauth#42] opened 2023-04-12 18:59 UTC
Export to a file that can be imported to other apps.

Not that I want to move but having the option would be great as this app is only available for android, when someone moves to android they still need the codes

**Comment by X1nto** [comment] 2023-04-18 19:45
Duplicate of #18

**Closed by X1nto** 2023-04-18 19:45 UTC

**Comment by pabloscloud** [comment] 2023-04-18 20:33
Sry
