### ISSUE TITLE
Images set for codes do not show after app relaunch

### ISSUE THREAD

**Issue by b2loo** [X1nto/Mauth#72] opened 2024-11-13 17:37 UTC
Hey again!

I've got Mauth set up with my Google Accounts' 2FA codes.
I've discovered that for some reason after I set an image and relaunching the application, the set image on longer shows.

It behaves as though one is still set, e.g. the default icon (just a G, presumed to be pulled from the first letter of the name given) not showing as it does on the second one that I have yet to set an icon for; it's just a blank circle, as if the image is supposed to be there but is not being rendered.

If you need any more information, let me know :)

**Comment by X1nto** [comment] 2024-11-13 20:03
Duplicate of #51. The issue will be fixed with the upcoming 0.9.0

**Closed by X1nto** 2024-11-13 20:03 UTC
